version: '3.9'

services:
  s1:
    image: ds-node-docker
    container_name: ds-s1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4444:4444'
      - '5555:5555'
    links:
      - s3
      - s5
    environment:
      SERVER_ID: 1
  s3:
    image: ds-node-docker
    container_name: ds-s3
    ports:
      - '4446:4446'
      - '5557:5557'
    environment:
      SERVER_ID: 3
  s5:
    image: ds-node-docker
    container_name: ds-s5
    ports:
      - '4448:4448'
      - '5559:5559'
    environment:
      SERVER_ID: 5