version: '3.9'

services:
  s2:
    image: ds-node-docker
    container_name: ds-s2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4445:4445'
      - '5556:5556'
    links:
      - s4
      - s6
    environment:
      SERVER_ID: 2
  s4:
    image: ds-node-docker
    container_name: ds-s4
    ports:
      - '4447:4447'
      - '5558:5558'
    environment:
      SERVER_ID: 4
  s6:
    image: ds-node-docker
    container_name: ds-s6
    ports:
      - '4449:4449'
      - '5560:5560'
    environment:
      SERVER_ID: 6