version: '3.9'

services:
  s1:
    image: ds-node-docker
    container_name: ds-s1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4444:4444'
      - '5555:5555'
    links:
      - s2
      - s3
    environment:
      SERVER_ID: 1
  s2:
    image: ds-node-docker
    container_name: ds-s2
    ports:
      - '4445:4445'
      - '5556:5556'
    environment:
      SERVER_ID: 2
  s3:
    image: ds-node-docker
    container_name: ds-s3
    ports:
      - '4446:4446'
      - '5557:5557'
    environment:
      SERVER_ID: 3