
export const responseTypes = {
    ROOM_CHANGE: "roomchange",
    SERVER_CHANGE: "serverchange",
    NEW_IDENTITY: "newidentity",
    LIST: "list",
    ROOMLIST: "roomlist",
    WHO: "who",
    ROOM_CONTENTS: "roomcontents",
    CREATE_ROOM: "createroom",
    DELETE_ROOM: "deleteroom",
    JOIN_ROOM: "joinroom",
    MOVE_JOIN: "movejoin",
    MESSAGE: "message",
    ROUTE: "route",
    QUIT: "quit",
    IS_CLIENT: "isclient",
    IS_CHATROOM: "ischatroom",
    CHATROOM_SERVER: "chatroomserver",
    BROADCAST_NEWIDENTITY: "broadcastnewidentity",
    BROADCAST_DELETEIDENTITY: "broadcastdeleteidentity",
    BROADCAST_CREATEROOM: "broadcastcreateroom",
    BROADCAST_DELETEROOM: "broadcastdeleteroom",
    BROADCAST_QUIT: "broadcastquit",
    INFORM_ROOMDELETION: "informroomdeletion",
    INFORM_CLIENTDELETION: "informclientdeletion"
}